export const orderStatusColorMap = {
  pending: "warning",
  shipped: "primary",
  delivered: "success",
  cancelled: "danger",
};
export const orders = [
  {
    orderId: 101,
    customerName: "John Doe",
    product: "Smartphone",
    quantity: 2,
    totalPrice: "$1200",
    status: "pending",
  },
  {
    orderId: 102,
    customerName: "Jane Smith",
    product: "Laptop",
    quantity: 1,
    totalPrice: "$1500",
    status: "shipped",
  },
  {
    orderId: 103,
    customerName: "Alice Johnson",
    product: "Headphones",
    quantity: 3,
    totalPrice: "$300",
    status: "delivered",
  },
  {
    orderId: 104,
    customerName: "Bob Brown",
    product: "Monitor",
    quantity: 1,
    totalPrice: "$400",
    status: "cancelled",
  },
  {
    orderId: 105,
    customerName: "Charlie Green",
    product: "Tablet",
    quantity: 2,
    totalPrice: "$800",
    status: "pending",
  },
  {
    orderId: 106,
    customerName: "Diana Blue",
    product: "Keyboard",
    quantity: 4,
    totalPrice: "$200",
    status: "delivered",
  },
  {
    orderId: 107,
    customerName: "Edward White",
    product: "Mouse",
    quantity: 3,
    totalPrice: "$150",
    status: "shipped",
  },
  {
    orderId: 108,
    customerName: "Fiona Black",
    product: "Desk Chair",
    quantity: 1,
    totalPrice: "$250",
    status: "cancelled",
  },
  {
    orderId: 109,
    customerName: "George Red",
    product: "Smartwatch",
    quantity: 2,
    totalPrice: "$500",
    status: "pending",
  },
  {
    orderId: 110,
    customerName: "Hannah Gold",
    product: "Gaming Console",
    quantity: 1,
    totalPrice: "$600",
    status: "shipped",
  },
  {
    orderId: 111,
    customerName: "Ian Violet",
    product: "Graphics Card",
    quantity: 1,
    totalPrice: "$700",
    status: "delivered",
  },
  {
    orderId: 112,
    customerName: "Julia Pink",
    product: "External Drive",
    quantity: 5,
    totalPrice: "$500",
    status: "pending",
  },
  {
    orderId: 113,
    customerName: "Kyle Orange",
    product: "Webcam",
    quantity: 2,
    totalPrice: "$200",
    status: "cancelled",
  },
  {
    orderId: 114,
    customerName: "Laura Cyan",
    product: "Printer",
    quantity: 1,
    totalPrice: "$350",
    status: "shipped",
  },
  {
    orderId: 115,
    customerName: "Mark Lime",
    product: "Router",
    quantity: 3,
    totalPrice: "$300",
    status: "pending",
  },
  {
    orderId: 116,
    customerName: "Nina Silver",
    product: "Fitness Tracker",
    quantity: 2,
    totalPrice: "$400",
    status: "delivered",
  },
  {
    orderId: 117,
    customerName: "Oscar Bronze",
    product: "Camera",
    quantity: 1,
    totalPrice: "$900",
    status: "shipped",
  },
  {
    orderId: 118,
    customerName: "Paula Indigo",
    product: "Microwave",
    quantity: 1,
    totalPrice: "$250",
    status: "cancelled",
  },
  {
    orderId: 119,
    customerName: "Quinn Navy",
    product: "Air Conditioner",
    quantity: 1,
    totalPrice: "$1200",
    status: "pending",
  },
  {
    orderId: 120,
    customerName: "Rachel Magenta",
    product: "Dishwasher",
    quantity: 1,
    totalPrice: "$800",
    status: "shipped",
  },
  {
    orderId: 121,
    customerName: "Steve Teal",
    product: "Oven",
    quantity: 1,
    totalPrice: "$700",
    status: "delivered",
  },
  {
    orderId: 122,
    customerName: "Tina Rose",
    product: "Refrigerator",
    quantity: 1,
    totalPrice: "$1000",
    status: "pending",
  },
];
export const orderStatusOptions = [
  { name: "Pending", uid: "pending" },
  { name: "Shipped", uid: "shipped" },
  { name: "Delivered", uid: "delivered" },
  { name: "Cancelled", uid: "cancelled" },
];
export const orderColumns = [
  { name: "Order ID", uid: "orderId", sortable: true },
  { name: "Customer Name", uid: "customerName", sortable: true },
  { name: "Product", uid: "product", sortable: true },
  { name: "Quantity", uid: "quantity", sortable: true },
  { name: "Total Price", uid: "totalPrice", sortable: true },
  { name: "Order Status", uid: "status", sortable: true },
  { name: "Actions", uid: "actions" },
];
export const ORDER_INITIAL_VISIBLE_COLUMNS = [
  "customerName",
  "product",
  "quantity",
  "totalPrice",
  "status",
  "actions",
];
export const productColumns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Name", uid: "name", sortable: true },
  { name: "Description", uid: "description", sortable: true },
  { name: "Price", uid: "price", sortable: true },
  { name: "Quantity", uid: "quantity", sortable: true },
  { name: "Status", uid: "status", sortable: true },
  { name: "Actions", uid: "actions" },
];
export const products = [
    {
      id: 1,
      name: "Smartphone",
      description: "A high-end smartphone with an OLED display.",
      price: "$1200",
      quantity: 10,
      status: "available",
    },
    {
      id: 2,
      name: "Laptop",
      description: "Lightweight and powerful laptop.",
      price: "$1500",
      quantity: 5,
      status: "out of stock",
    },
    {
      id: 3,
      name: "Headphones",
      description: "Wireless headphones with noise cancellation.",
      price: "$300",
      quantity: 20,
      status: "available",
    },
    {
      id: 4,
      name: "Keyboard",
      description: "Backlit mechanical keyboard.",
      price: "$100",
      quantity: 50,
      status: "available",
    },
    {
      id: 5,
      name: "Camera",
      description: "Professional digital camera.",
      price: "$900",
      quantity: 2,
      status: "limited",
    },
    {
      id: 6,
      name: "Smartwatch",
      description: "Fitness tracking smartwatch with a sleek design.",
      price: "$200",
      quantity: 25,
      status: "available",
    },
    {
      id: 7,
      name: "Tablet",
      description: "Portable tablet with a 10-inch display.",
      price: "$400",
      quantity: 15,
      status: "available",
    },
    {
      id: 8,
      name: "Gaming Console",
      description: "Next-generation gaming console.",
      price: "$500",
      quantity: 8,
      status: "out of stock",
    },
    {
      id: 9,
      name: "Monitor",
      description: "4K UHD monitor with HDR support.",
      price: "$300",
      quantity: 18,
      status: "available",
    },
    {
      id: 10,
      name: "Mouse",
      description: "Ergonomic wireless mouse.",
      price: "$50",
      quantity: 100,
      status: "available",
    },
    {
      id: 11,
      name: "Router",
      description: "High-speed Wi-Fi router for gaming and streaming.",
      price: "$150",
      quantity: 12,
      status: "limited",
    },
    {
      id: 12,
      name: "External Hard Drive",
      description: "1TB portable external hard drive.",
      price: "$70",
      quantity: 30,
      status: "available",
    },
    {
      id: 13,
      name: "Drone",
      description: "Compact drone with 4K video recording capabilities.",
      price: "$600",
      quantity: 4,
      status: "out of stock",
    },
    {
      id: 14,
      name: "Webcam",
      description: "1080p HD webcam for video conferencing.",
      price: "$80",
      quantity: 40,
      status: "available",
    },
    {
      id: 15,
      name: "Speakers",
      description: "Bluetooth speakers with powerful sound.",
      price: "$120",
      quantity: 22,
      status: "available",
    },
    {
      id: 16,
      name: "Power Bank",
      description: "Portable power bank with fast charging support.",
      price: "$40",
      quantity: 75,
      status: "available",
    },
    {
      id: 17,
      name: "Projector",
      description: "Mini projector for home entertainment.",
      price: "$250",
      quantity: 6,
      status: "limited",
    },
    {
      id: 18,
      name: "VR Headset",
      description: "Immersive virtual reality headset.",
      price: "$350",
      quantity: 3,
      status: "out of stock",
    },
    {
      id: 19,
      name: "Fitness Tracker",
      description: "Waterproof fitness tracker with heart rate monitor.",
      price: "$75",
      quantity: 45,
      status: "available",
    },
    {
      id: 20,
      name: "Smart Light Bulb",
      description: "Wi-Fi-enabled smart light bulb with color-changing options.",
      price: "$25",
      quantity: 200,
      status: "available",
    },
  ];
  
export const productStatusOptions = [
  { name: "Available", uid: "available" },
  { name: "Out of Stock", uid: "out of stock" },
  { name: "Limited", uid: "limited" },
  { name: "Inactive", uid: "inactive" },
];

export const productStatusColorMap = {
  limited: "warning",
  inactive: "primary",
  available: "success",
  "out of stock": "danger",
};
export const PRODUCT_INITIAL_VISIBLE_COLUMNS = [
  "id",
  "name",
  "price",
  "quantity",
  "description",
  "status",
  "actions",
];

export const customers = [
    {
      id: 1,
      name: "John Smith",
      email: "john.smith@example.com",
      phone: "123-456-7890",
      address: "123 Elm Street, Springfield, USA",
      status: "active",
    },
    {
      id: 2,
      name: "Jane Doe",
      email: "jane.doe@example.com",
      phone: "987-654-3210",
      address: "456 Maple Avenue, New York, USA",
      status: "inactive",
    },
    {
      id: 3,
      name: "Michael Brown",
      email: "michael.brown@example.com",
      phone: "555-123-4567",
      address: "789 Oak Lane, Chicago, USA",
      status: "active",
    },
    {
      id: 4,
      name: "Emily Davis",
      email: "emily.davis@example.com",
      phone: "444-987-6543",
      address: "321 Pine Road, Houston, USA",
      status: "active",
    },
    {
      id: 5,
      name: "William Johnson",
      email: "william.johnson@example.com",
      phone: "222-333-4444",
      address: "654 Cedar Drive, Los Angeles, USA",
      status: "inactive",
    },
    {
      id: 6,
      name: "Sophia Martinez",
      email: "sophia.martinez@example.com",
      phone: "111-222-3333",
      address: "987 Birch Boulevard, Miami, USA",
      status: "active",
    },
    {
      id: 7,
      name: "James Wilson",
      email: "james.wilson@example.com",
      phone: "666-555-4444",
      address: "135 Willow Street, Seattle, USA",
      status: "active",
    },
    {
      id: 8,
      name: "Olivia Anderson",
      email: "olivia.anderson@example.com",
      phone: "777-888-9999",
      address: "246 Aspen Court, Dallas, USA",
      status: "inactive",
    },
    {
      id: 9,
      name: "Benjamin Moore",
      email: "benjamin.moore@example.com",
      phone: "999-888-7777",
      address: "369 Elmwood Avenue, Boston, USA",
      status: "active",
    },
    {
      id: 10,
      name: "Isabella Taylor",
      email: "isabella.taylor@example.com",
      phone: "333-222-1111",
      address: "741 Poplar Street, Denver, USA",
      status: "active",
    },
    {
      id: 11,
      name: "Liam White",
      email: "liam.white@example.com",
      phone: "888-777-6666",
      address: "852 Cypress Lane, Austin, USA",
      status: "inactive",
    },
    {
      id: 12,
      name: "Mia Martin",
      email: "mia.martin@example.com",
      phone: "555-444-3333",
      address: "963 Chestnut Boulevard, Atlanta, USA",
      status: "active",
    },
    {
      id: 13,
      name: "Elijah Harris",
      email: "elijah.harris@example.com",
      phone: "111-444-5555",
      address: "147 Redwood Drive, Orlando, USA",
      status: "inactive",
    },
    {
      id: 14,
      name: "Charlotte Clark",
      email: "charlotte.clark@example.com",
      phone: "222-555-6666",
      address: "258 Spruce Road, Phoenix, USA",
      status: "active",
    },
    {
      id: 15,
      name: "Alexander Lewis",
      email: "alexander.lewis@example.com",
      phone: "777-222-3333",
      address: "369 Hemlock Avenue, San Francisco, USA",
      status: "active",
    },
    {
      id: 16,
      name: "Amelia Young",
      email: "amelia.young@example.com",
      phone: "444-888-1111",
      address: "951 Juniper Street, Nashville, USA",
      status: "inactive",
    },
    {
      id: 17,
      name: "Henry Walker",
      email: "henry.walker@example.com",
      phone: "333-111-2222",
      address: "753 Dogwood Lane, Portland, USA",
      status: "active",
    },
    {
      id: 18,
      name: "Evelyn Hall",
      email: "evelyn.hall@example.com",
      phone: "666-999-4444",
      address: "159 Hawthorn Road, Las Vegas, USA",
      status: "active",
    },
    {
      id: 19,
      name: "Lucas King",
      email: "lucas.king@example.com",
      phone: "888-444-7777",
      address: "357 Aspen Drive, Charlotte, USA",
      status: "inactive",
    },
    {
      id: 20,
      name: "Harper Scott",
      email: "harper.scott@example.com",
      phone: "111-666-8888",
      address: "864 Magnolia Avenue, San Diego, USA",
      status: "active",
    },
];
export const customersColumns = [
    { name: "ID", uid: "id", sortable: true },
    { name: "Name", uid: "name", sortable: true },
    { name: "Email", uid: "email", sortable: true },
    { name: "Phone", uid: "phone", sortable: true },
    { name: "Address", uid: "address", sortable: true },
    { name: "Status", uid: "status", sortable: true },
    { name: "Actions", uid: "actions" },
  ];

  export const customersStatusOptions = [
    { name: "Active", uid: "active" },
    { name: "Inactive", uid: "inactive" },
  ];
  
  export const customersStatusColorMap = {
    inactive: "danger",
    active: "success",
  };
  export const CUSTOMERS_INITIAL_VISIBLE_COLUMNS = [
    "id",
    "name",
    "email",
    "phone",
    "address",
    "status",
    "actions",
  ];